spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  neo4j:
    pool:
      idle-time-before-connection-test:
server:
  port: 8888
